"""empty message

Revision ID: 7ea6e2851d05
Revises: 
Create Date: 2020-12-17 00:13:39.306213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea6e2851d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('s_bal', sa.Integer(), nullable=True),
    sa.Column('marks', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('teacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
